//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSearchAppXamarin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameSearchAppXamarin.Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deteils.
        /// </summary>
        public static string GameItemDeteils {
            get {
                return ResourceManager.GetString("GameItemDeteils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string GameItemLike {
            get {
                return ResourceManager.GetString("GameItemLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string GameItemShare {
            get {
                return ResourceManager.GetString("GameItemShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnLike.
        /// </summary>
        public static string GameItemUnlike {
            get {
                return ResourceManager.GetString("GameItemUnlike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string GamePageSearchPlaceHolder {
            get {
                return ResourceManager.GetString("GamePageSearchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string InfoGameDescription {
            get {
                return ResourceManager.GetString("InfoGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string InfoGameLastUpdate {
            get {
                return ResourceManager.GetString("InfoGameLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string InfoGameMoreInfo {
            get {
                return ResourceManager.GetString("InfoGameMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raiting.
        /// </summary>
        public static string InfoGameRaiting {
            get {
                return ResourceManager.GetString("InfoGameRaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website .
        /// </summary>
        public static string InfoGameWebSite {
            get {
                return ResourceManager.GetString("InfoGameWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string MenuGameLabel {
            get {
                return ResourceManager.GetString("MenuGameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked Games.
        /// </summary>
        public static string MenuLikedGameLabel {
            get {
                return ResourceManager.GetString("MenuLikedGameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Options.
        /// </summary>
        public static string MenuOptionSearchLabel {
            get {
                return ResourceManager.GetString("MenuOptionSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuPageTitle {
            get {
                return ResourceManager.GetString("MenuPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuSettingLabel {
            get {
                return ResourceManager.GetString("MenuSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Querry.
        /// </summary>
        public static string OptionSearchAddQuerry {
            get {
                return ResourceManager.GetString("OptionSearchAddQuerry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qyerry.
        /// </summary>
        public static string OptionSearchQuerry {
            get {
                return ResourceManager.GetString("OptionSearchQuerry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string OptionSearchType {
            get {
                return ResourceManager.GetString("OptionSearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string SearchOptionsAccept {
            get {
                return ResourceManager.GetString("SearchOptionsAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SearchOptionsCancel {
            get {
                return ResourceManager.GetString("SearchOptionsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkTheme.
        /// </summary>
        public static string SettingDarkTheme {
            get {
                return ResourceManager.GetString("SettingDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingLanguageLabel {
            get {
                return ResourceManager.GetString("SettingLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightTheme.
        /// </summary>
        public static string SettingLightTheme {
            get {
                return ResourceManager.GetString("SettingLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SettingSelectButton {
            get {
                return ResourceManager.GetString("SettingSelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingThemeLabel {
            get {
                return ResourceManager.GetString("SettingThemeLabel", resourceCulture);
            }
        }
    }
}
